In [1]:
import torch

In [4]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [11]:
#Standard numpy-like indexing and slicing:
tensor = torch.ones(4, 4)
print("First Row: ", tensor[0])
print("First Column ", tensor[:, 0])
print("last Column ", tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First Row:  tensor([1., 1., 1., 1.])
First Column  tensor([1., 1., 1., 1.])
last Column  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
#Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [15]:
# Arithmetic operations
# This computes the matrix multiplication between two tensors. 
#y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

z1 =tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [17]:
# Single-element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
#In-place operations
print(tensor, "\n")
tensor.add_(5)