In [3]:
import numpy as np
from numpy import random

In [4]:
list_1 = [1,2,3,4,5,6,7,8,9,10]

In [5]:
np_arr_1 = np.array(list_1, dtype=np.int8)#create an array from variable list_1

In [6]:
np_arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [7]:
m_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
np_arr_2 = np.array(m_list_1)#creating a matrix

In [8]:
np_arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(1, 100)# displays values from 1 to 100

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.arange(1, 100, 3)# 3 is step its like interval

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [12]:
np.linspace(0, 5, 7)# its like saying return 7 values with equal interval from 0 to 5

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [13]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [14]:
np.zeros(4)#displays 4 zeros, you can also display ones

array([0., 0., 0., 0.])

In [16]:
np.ones((5, 6))# multidimensional array of 5 rows and 6 columns

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np_arr_2.size# displays the size of that array

9

In [19]:
np_arr_2.dtype#displays the data type of that array

dtype('int32')

In [22]:
np.random.randint(10, 50, 5)#generates random variables from 10 to 50 with interval of 5

array([29, 31, 23, 46, 44])

In [25]:
np.random.randint(10, 50, size=(2,3))#generates multidimensional array(2rows 3 columns)with values from 10 to 50 

array([[39, 46, 31],
       [15, 46, 49]])

In [26]:
 np.random.randint?# put a question mark to display documentation

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 