In [1]:
import numpy as np

In [4]:
m_list_1  = [[1,2,3],[4,5,6],[7,8,9]]
             

In [5]:
np_m_arr_1 = np.array(m_list_1)

In [6]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np_m_arr_1[0, 0] = 2 #changes the value in the first row first column to 2

In [9]:
np_m_arr_1

array([[2, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np_m_arr_1.itemset((0, 1), 1)

In [11]:
np_m_arr_1

array([[2, 1, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np_m_arr_1.shape #gives the dimension of the array

(3, 3)

In [13]:
np_m_arr_1[0, 1] #displays the value in the first row first column ----- also you can do as below

1

In [14]:
np_m_arr_1.item(0, 1)# works the same as above  #notice we put brackets in this case

1

In [17]:
print("np_m_arr_1\n", np_m_arr_1)
np.take(np_m_arr_1, [0, 3, 6])#displays the first ,third and sixth values from the array.

np_m_arr_1
 [[2 1 3]
 [4 5 6]
 [7 8 9]]


array([2, 4, 7])

In [18]:
np.put(np_m_arr_1, [0, 3, 6], [10, 10, 10])#changes the first, third and sixth values to 10, 10 ,10

In [19]:
np_m_arr_1

array([[10,  1,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [23]:
list_1 = [1,2,3,4,5,6,7,8,9,10]
np_arr_1 = np.array(list_1)
np_arr_1[:5:2]#displays from the first item to the fifth with a step of 2


array([1, 3, 5])

In [25]:
np_m_arr_1[:,1]#slices all values of the second column

array([1, 5, 8])

In [26]:
np_m_arr_1[::-1]#flips the matrix# do research on flipping

array([[10,  8,  9],
       [10,  5,  6],
       [10,  1,  3]])

In [27]:
evens = np_m_arr_1[np_m_arr_1%2 == 0]#displys even numbers

In [28]:
evens

array([10, 10,  6, 10,  8])

In [29]:
np_m_arr_1[np_m_arr_1 > 5]#displays values greater than 5

array([10, 10,  6, 10,  8,  9])

In [31]:
np_m_arr_1[(np_m_arr_1 > 5) & (np_m_arr_1 < 9)]#displays values greater than 5 and less than 5

array([6, 8])

In [32]:
np_m_arr_1[(np_m_arr_1 > 5) | (np_m_arr_1 == 10)]#displays value greater than 5 or greater than 10 

array([10, 10,  6, 10,  8,  9])

In [36]:
np.unique(np_m_arr_1)#displays unique values

array([ 1,  3,  5,  6,  8,  9, 10])